### ISSUE TITLE
Invalid project name with build_directory results in obscure Docker error

### ISSUE THREAD

**Issue by jagregory** [charleskorn/batect#101]
If you specify a project name that includes upper case letters or spaces, and use a container that uses `build_directory`, when the container is built you get a relatively unclear error message:

> Building image failed: invalid reference format: repository name must be lowercase

It's not immediately obvious that the project name ends up being used as part of the docker image (although in hindsight it makes sense).

**Comment by charleskorn** [comment]
Hey @jagregory, thanks for letting me know about this. We should definitely be doing some validation on the project name (and probably the container name as well) to prevent issues like this.

**Comment by charleskorn** [comment]
Thanks again for your feedback @jagregory - I've fixed this issue and I'll push out a release with the fix shortly.

In the meantime, you can grab the latest version from the files section of https://bintray.com/charleskorn/batect/batect/0.33.0-dev.0.15%2B57c558f if you want to try out the fix before I publish the release. (It might take ~20 minutes for the build and publish to finish.)
