### ISSUE TITLE
YAML deserialisation errors are obscure

### ISSUE THREAD

**Issue by jagregory** [charleskorn/batect#102]
I accidentally defined `volumes` as a string instead of an array:

```yaml
container:
  volumes: .:/code
```

The resulting error isn't the clearest:

> batect.yml: Could not load configuration file: Size must be known in advance when using READ_ALL

I assumed it was a syntax error in my YAML, but from a YAML perspective it's correct. So it must be when it's trying to deserialize valid YAML into an incompatible data structure.

**Comment by charleskorn** [comment]
Hey @jagregory, thanks for the feedback. You're right, this error message isn't very clear at all. I'll take a look and improve it.

**Comment by charleskorn** [comment]
I've pushed a fix for this and it'll be in the next release - thanks again for your feedback @jagregory.
