### ISSUE TITLE
Maybe interesting: Toast, written in Rust

### ISSUE THREAD

**Issue by Byron-TW** [charleskorn/batect#108]
Hi @charleskorn ,

I had a look at [this tool, Toast](https://github.com/stepchowfun/toast), and it looked somewhat similar to Batect. One major difference seems to be that there is only a single (shared) image across tasks, and that there is no orchestration across containers, limiting its use for tests.

The reason I post it here is to possibly give you inspiration for further developing Batect.

Cheers,
Sebastian

**Comment by charleskorn** [comment]
Hey @Byron-TW, thanks for sharing. That tool looks really interesting, I like its use of caching to speed things up. I'll definitely keep it in mind as I develop further features for batect!
