### ISSUE TITLE
More logging options

### ISSUE THREAD

**Issue by ineffyble** [charleskorn/batect#115]
It can be very difficult to troubleshoot things when you're using batect.

As an example, if I have a task that start my app code, and has a dependency on a localstack container, I only have access to the app logs (via stdout). I have no way to see the logs of the localstack container at all.

Things that would be useful:

- An option to keep stopped containers so I can `docker logs` them, even if they don't fail
- The ability to interleave logs from all running containers to stdout (like docker-compose does)
- An option to save container logs to a file

**Comment by charleskorn** [comment]
Hey @ineffyble, thanks for the feedback. I agree this is something that batect could do better.

> An option to keep stopped containers so I can `docker logs` them, even if they don't fail

This wouldn't be too hard to implement - this is something I could do in the short term

> The ability to interleave logs from all running containers to stdout (like docker-compose does)

This would be much more complex to implement, but it would also be the best user experience - this is probably more of a long-term feature

> An option to save container logs to a file

If you had the other two options available, would you still want / need this?

**Comment by charleskorn** [comment]
I've just added the ability to keep the stopped containers running (provide `--no-cleaup-after-success` or `--no-cleanup`) and this will be part of the next release.

**Comment by charleskorn** [comment]
I've added the ability to show output from all containers interleaved (run the task with `--output all`), and this will be part of the next release. I'm not going to implement the ability to save logs to a file just yet - if you feel that `--output all` doesn't satisfy your needs enough, please submit a new issue.

Thanks again for your feedback @ineffyble!

**Comment by camjackson** [comment]
Yaaas I was just coming here to chime in that this feature would be super helpful, and it's already done! 😁

Time to go update all my repos to 0.36.0!
