### ISSUE TITLE
Improve message produced after running upgrade

### ISSUE THREAD

**Issue by ekamara** [charleskorn/batect#12]
After running the upgrade task, you get notified that batect has been upgraded which could be read to imply that both the wrapper script and the jar file have been upgraded whereas only the wrapper script has been upgraded to the latest version. 

The upgrade message should state explicitly that only the wrapper is being upgraded and that the jar file will be upgraded when you next run batect

**Comment by charleskorn** [comment]
Thanks for the feedback @ekamara. That message could definitely be a bit clearer.

**Comment by charleskorn** [comment]
I've improved some of the messages, but I don't want to explicitly mention the JAR file as at some point in the (hopefully near) future, we won't be using JAR files anymore. 

Thanks again for the feedback @ekamara!
