### ISSUE TITLE
Override volume configuration at runtime

### ISSUE THREAD

**Issue by jmewes** [charleskorn/batect#120]
Hi,

When trying out Batect, a colleague of mine asked whether it's possible to override container volumes at runtime, something like this:

```
./batect --volume local=/tmp/code,container=/code,options=cached myTask
```

Looking the [container volume configuration](https://batect.charleskorn.com/config/Containers.html#volumes) in the docs, it seems like it's not possible at the moment.

Do you think this is a feature which should be supported?

Kind regards

**Comment by charleskorn** [comment]
Hi @jmewes, thanks for the feedback. It's an interesting idea, and I'd like to understand your use case a little bit more - is there a reason why putting volume mounts in the configuration file is unsuitable?

**Comment by jmewes** [comment]
Hi @charleskorn ,

My colleague brought up the question when reviewing a pull request which I have created. After having the opportunity to explain the semantics of the `batect.yml` file to him personally, it turned out that for our use case (mounting some data into the container for creating a PDF file out of it) a relative path is sufficient.

Thank you for your time to consider our question. I'll close the issue as we don't actually need this feature.
