### ISSUE TITLE
Allow for quiet batect download from batect script (no -#)

### ISSUE THREAD

**Issue by eichelkrauta** [charleskorn/batect#126]
Currently, the bootstrapping batect script downloads the batect jar with a -# flag, causing the following to happen in certain environments:
<img width="589" alt="Screen Shot 2019-06-17 at 4 06 30 PM" src="https://user-images.githubusercontent.com/8661309/59864272-0a3bce80-934c-11e9-91c2-8840bad5fe81.png">

I would like an optional flag added to the bootstrapping script to address this issue in these environments. Suggested: a `--quiet` or `-q` flag to suppress downloading output from the bootstrapping script.

**Comment by charleskorn** [comment]
Resolved with #129.
