### ISSUE TITLE
Allow a task or container to override an image's ENTRYPOINT

### ISSUE THREAD

**Issue by camjackson** [charleskorn/batect#178]
Say I'm using an image that someone else built, which has set `ENTRYPOINT someTool` in its Dockerfile. When using that image in batect, I can do `command: someCmd`, and inside the container it will run `someTool someCmd`. That's all expected behaviour.

Where it gets tricky is if I want to override the `ENTRYPOINT` that the image has. If I want to get an interactive shell in the container for debugging, or if I want to run two commands with `&&`, I don't think it's possible. When I set `command: sh`, it ends up running `someTool sh` in the container, which is not what I wanted.

When using `docker run` from the CLI, it's easy to fix - I can just set the `--entrypoint` flag to whatever I need. But AFAICT batect doesn't let me set the entrypoint on either a container or a task, which means the only way to override it is to create a new Dockerfile and build my own image with a different `ENTRYPOINT`.

Would you be interested in a PR that allows setting `entrypoint` on tasks or containers or both?

**Comment by charleskorn** [comment]
Hey @camjackson, thanks for the detailed suggestion! I'd love to see a PR for this, and I'm happy to give you some pointers on where to get started if you'd like.
