### ISSUE TITLE
NoSuchElementException: Element Error is missing

### ISSUE THREAD

**Issue by Sami5** [charleskorn/batect#20]
I'm receiving the following error when running a task in GoCD:

<img width="1113" alt="screen shot 2018-11-08 at 10 51 07 am" src="https://user-images.githubusercontent.com/16506862/48168668-53eb2200-e344-11e8-814e-06237987ebd6.png">

**Comment by charleskorn** [comment]
Are you able to run the task with logging enabled (`--log-file=<some file>`) and send it to me at me@charleskorn.com?

Please double-check that the log file does not contain any sensitive information before sending it to me (it will contain things like paths to your configuration file, all of your environment variables and some version information).

**Comment by Sami5** [comment]
Hmm are you saying to run that locally or on GoCD? 😕

Samantha

On 8 Nov 2018, at 4:11 pm, Charles Korn <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you able to run the task with logging enabled (--log-file=<some file>) and send it to me at me@charleskorn.com<mailto:me@charleskorn.com>?

Please double-check that the log file does not contain any sensitive information before sending it to me (it will contain things like paths to your configuration file, all of your environment variables and some version information).

**Comment by charleskorn** [comment]
On GoCD if you can.

**Comment by Sami5** [comment]
I'll try to but I don't know when I'll have a free moment to test it on GoCD again as we have two squads working off the same pipeline.

Samantha

On 8 Nov 2018, at 4:11 pm, Charles Korn <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you able to run the task with logging enabled (--log-file=<some file>) and send it to me at me@charleskorn.com<mailto:me@charleskorn.com>?

Please double-check that the log file does not contain any sensitive information before sending it to me (it will contain things like paths to your configuration file, all of your environment variables and some version information).

**Comment by charleskorn** [comment]
No worries, thanks @Sami5!

**Comment by charleskorn** [comment]
Hi @Sami5, were you able to get that log file?

**Comment by Sami5** [comment]
No sorry I haven't had the chance. It's been a rush here.



On 20 Nov 2018, at 10:30 am, Charles Korn <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Sami5<https://github.com/Sami5>, were you able to get that log file?

**Comment by charleskorn** [comment]
No worries, let me know when you get a chance to take a look.

**Comment by charleskorn** [comment]
Hi @Sami5, did you ever get a chance to get that log file?

**Comment by Sami5** [comment]
Hi Charles, unfortunately I don't think I'd be able to get this information. You can probably close this issue.

**Comment by charleskorn** [comment]
No worries, thanks for the feedback. Are you still seeing this issue?

**Comment by Sami5** [comment]
We are't using the latest version so I can't say. But if we run into this again, I'll try your above steps and let you know.

**Comment by ineffyble** [comment]
I'm seeing this on CircleCI with batect 0.27.1 now. Running locally it works right, but on CircleCI, all my jobs end with this error.

**Comment by charleskorn** [comment]
I've been able to identify the problem (thanks @ineffyble for the logs) - it's an issue running batect against Docker version 17.10 and earlier. I've got a fix ready and I'll push out a release shortly.

Thanks for your feedback!
