### ISSUE TITLE
Ability to set the CIDR range of the network created

### ISSUE THREAD

**Issue by priorax** [charleskorn/batect#207]
Thanks to the many network re-architectures over the years, my corporate VPN pushes out IP routes for most of the RFC1918 space (with the majority of our infrastructure being on the same IP range as the docker default network)
This means that when I run `docker network create` I get the following error:
```
$ docker network create example
Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
```

This can be overcome by specifying a CIDR range manually

```
$ docker network create example --subnet 192.168.150.0/24
28b97d72bf430c61c16b9a7cb55feea75ff617ac0b08bb2d84f28927b8a1e1a4
```

At a Daemon level, I have set the bip and cidr range to use for `docker0` using the docker daemon settings and have verified this all works fine, this is only problematic once creating new networks apparently.

Due to this I would like an optional project-level setting to be able to specify the IP range for the network that batect is managing.

When running this in batect a batect task, I get the following message:
```
Error: Could not create network for task.
could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
```
This does seem to be a carry-over from docker, but I'm just wondering if there is a way to handle it from batect (as there seems to be a workaround for handling creation manually)

**Comment by charleskorn** [comment]
Hi @priorax, thanks for the suggestion! Have you tried setting `default-address-pools` for your daemon as discussed in https://github.com/moby/moby/pull/29376? That looks like it might solve the issue - `default-address-pools` defines the pools that Docker can use by default when creating networks.

**Comment by priorax** [comment]
Hi @charleskorn , sorry for the delay in getting back to you.
That worked beautifully!
I'll happily close this issue off.

**Comment by charleskorn** [comment]
> any hint on how to determine the correct default-address-pools when running OpenVPN?

You'll need to define a pool of private IP addresses ([this Wikipedia page](https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses) has a table showing the reserved private ranges) that doesn't overlap with the address range used by your VPN. Unfortunately I don't use OpenVPN so I can't provide more hints as to how to work out what the address range used by your VPN is, but whoever administers your VPN should be able to tell you.
