### ISSUE TITLE
batect doesn't appear to work with Minikube docker daemon

### ISSUE THREAD

**Issue by aidansteele** [charleskorn/batect#278]
When I use minikube, I set the following environment variables:

```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.64.3:2376"
export DOCKER_CERT_PATH="/Users/aidan.steele/.minikube/certs"
```

This fails to run my task and returns the following error:

> Docker is not installed, not running or not compatible with batect: Unexpected status line:

**Comment by charleskorn** [comment]
Hey @aidansteele, thanks for the feedback. I'll take a look.
