### ISSUE TITLE
batect not propagating host's /etc/resolv.conf to containers

### ISSUE THREAD

**Issue by chandantp** [charleskorn/batect#296]
batect is not propagating host's `/etc/resolv.conf` to the container. As a result, the DNS resolution fails. The example using `alpine` image is shown below.

Note that on running the same container using `docker`, the name resolution succeeds. 
Further, on mounting host's `/etc/resolv.conf` to the container in the batect container definition and login to the container, the DNS resolution succeeds. 

batect version = `0.38.0`
docker image = `alpine:3.10.3` (this is just an example but issue is seen with other images also)

```
$ ./batect shell
Running shell...
deploy-env: running bash
bash-5.0$ nslookup forwardproxy
nslookup: can't resolve '(null)': Name does not resolve
nslookup: can't resolve 'forwardproxy': Try again
```
```
$ docker run -it alpine:3.10.3 sh
bash-5.0# nslookup forwardproxy
nslookup: can't resolve '(null)': Name does not resolve
Name:      forwardproxy
Address 1: 10.39.66.83 ip-10-39-66-83.ap-southeast-2.compute.internal
Address 2: 10.39.66.137 ip-10-39-66-137.ap-southeast-2.compute.internal
Address 3: 10.39.66.227 ip-10-39-66-227.ap-southeast-2.compute.internal
```

**Comment by charleskorn** [comment]
Hey @chandantp, thanks for the feedback. This may be an issue with how Docker does DNS resolution in non-default networks. By default, it will set up a DNS server of its own that will delegate to the host's `resolv.conf` if it can't answer the query. (https://docs.docker.com/v17.09/engine/userguide/networking/configure-dns/ has more details.)

If you attempt to resolve the name with the full domain name (eg. instead of `nslookup forwardproxy`, use `nslookup forwardproxy.mycompany.com`), does it work?

**Comment by chandantp** [comment]
Docker version: `19.03.5, build 633a0ea` (missed providing this earlier)

If the full domain name is provided, the DNS resolution is successful as can be seen below.
```
$ ./batect shell
Running shell...
deploy-env: running sh
/code $ nslookup forwardproxy.extnp.mycompany.com.au
nslookup: can't resolve '(null)': Name does not resolve
Name:      forwardproxy.extnp.mycompany.com.au
Address 1: 10.39.66.137 ip-10-39-66-137.ap-southeast-2.compute.internal
Address 2: 10.39.66.227 ip-10-39-66-227.ap-southeast-2.compute.internal
Address 3: 10.39.66.83 ip-10-39-66-83.ap-southeast-2.compute.internal
```

Apparently, when the container is run using `batect`, the DNS resolution is not being delegated to the host's `resolv.conf` when the embedded DNS server is unable to resolve the hostname. The same however works when the container is run directly using `docker` CLI.

Another thing to be noted is the difference in the content of `resolv.conf` when the container is run using `batect` versus `docker`. Per the link you sent above, I expected the nameserver to be the embedded DNS server (`127.0.0.11`) in both cases. However, as you can see below, the `batect` run `alpine` container shows the nameserver to be the embedded DNS server where as the `docker` run `alpine` container shows the host's nameservers. Is this significant?

```
$ ./batect shell
Running shell...
deploy-env: running sh
/code $ cat /etc/resolv.conf 
search extnp.mycompany.com.au
nameserver 127.0.0.11
options timeout:2 attempts:2 rotate ndots:0
```
```
$ docker run -it alpine:3.10.3 sh
/ # cat /etc/resolv.conf 
options timeout:2 attempts:2 rotate
; generated by /usr/sbin/dhclient-script
search extnp.mycompany.com.au
nameserver 10.99.91.101
nameserver 10.99.92.102
```

**Comment by charleskorn** [comment]
The other big difference between `docker run ...` and batect is that batect also starts a separate Docker network for each task, which results in the behaviour described in that page I linked to.

Can you please try running the following and let me know if you run into the same behaviour?

```shell
docker network create test-network
docker run --rm -it --network test-network alpine:3.10.3 sh
# To clean up once you're done:
docker network rm test-network
```

This will reveal whether it is an issue with batect or Docker itself.

**Comment by chandantp** [comment]
Yes, I run into the same behaviour with the above commands as can be seen below:
```
$ docker run --rm -it --network test-network alpine:3.10.3 sh
/ # nslookup forwardproxy
nslookup: can't resolve '(null)': Name does not resolve
nslookup: can't resolve 'forwardproxy': Try again
```

**Comment by charleskorn** [comment]
OK, in that case, it's not an issue with batect, but an issue with Docker. I can't find this issue reported elsewhere, so I'd suggest filing an issue with them.

In the meantime, configuring `--dns-search` for your Docker daemon (see https://docs.docker.com/engine/reference/commandline/dockerd/) may resolve the issue.
