### ISSUE TITLE
Moving to Kotlin/native, away from JVM: stories

### ISSUE THREAD

**Issue by binkley** [charleskorn/batect#40]
I'm excited to see in your "Roadmap" doc (first rate docs, btw) that you intent to move to Kotlin/native.  This appears a sound choice.

I looked through the issue tracker, and didn't see much around this aspiration.  If you could post particular areas of batect where you'd like to see the migration begin, it might garner volunteers.

**Comment by charleskorn** [comment]
Great idea, thanks for the suggestion @binkley.

Most of the work involved is not batect-specific, and largely revolves around library support for Kotlin/Native. 

For example, last time I checked, Spek didn't yet support Kotlin/Native but there was talk of doing that.  Looking at the code now, it looks like they've restructured the library to support it in the future, but haven't yet implemented it. 

Once we're able to run the tests under Kotlin/Native, that then opens the floodgates to all the other things that need to be migrated (which will largely revolve around replacing JVM libraries with their native equivalents - eg. replacing commons-compress with something like libarchive).

**Comment by binkley** [comment]
Thanks for a solid answer.  My takeaway is progress on Kotlin/native for batect is blocked by other dependencies.

**Comment by charleskorn** [comment]
I'm going to close this for now to keep the issues list on GitHub clean, but I will definitely add some stories once the basic building blocks are in place for the migration.
