### ISSUE TITLE
Migrate build to Kotlin DSL

### ISSUE THREAD

**Issue by binkley** [charleskorn/batect#45]
I'm uncertain from the roadmap the degree to which this is a Kotlin project.  Lately I've been trying Gradle 5.0 with Kotlin DSL 5.0 on small projects.  Migrating was straight-forward:

https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/

If you have an interest, I will find some time for a PR to your repo.

**Comment by charleskorn** [comment]
I'm definitely interested (I've been using the Kotlin DSL on another project and like it). 

The only drawback to migrating would be the loss of Dependabot support, but they are working on this (https://github.com/dependabot/feedback/issues/172), and I think the other benefits outweigh the temporary loss of Dependabot. 

I'd love any PRs you have time for - please feel free to send them through!

**Comment by charleskorn** [comment]
I'm going to close this due to inactivity, but if you're still interested in submitting a PR, that would be great!
