### ISSUE TITLE
Weird dependency execution order

### ISSUE THREAD

**Issue by ineffyble** [charleskorn/batect#53]
I've run into a situation where tasks are executing in an unexpected fashion. I've replicated this situation with the `batect.yml` below.

**Expected behaviour:** makeTheSandwich runs _before_ takeABiteOfTheSandwich

Is there something I'm missing in my dependency tree that's causing it to run in this order?

[batect.yml.txt](https://github.com/charleskorn/batect/files/2762493/batect.yml.txt)

**Comment by charleskorn** [comment]
Thanks for the feedback @ineffyble. Just to be clear, which task are you running? (ie. `./batect <some-task-name-here>`)

**Comment by ineffyble** [comment]
Oops, sorry. `./batect sandwichHasBeenEaten`

**Comment by charleskorn** [comment]
Right, so if I understand correctly, the order in `prerequisites` is not respected?

I would expect the execution order to be:

* `getSandwichContents`
* `putContentsInBread`
* `prepareTheTable`
* `makeTheSandwich`
* `takeABiteOfTheSandwich`
* `eatTheSandwich`
* `sandwichHasBeenEaten`

If that's not what's happening then this sounds like a bug, not something you're missing in your configuration.

**Comment by ineffyble** [comment]
That's right - they're running in the wrong order.

Good to know it is a bug and just not me goofing up.

**Comment by charleskorn** [comment]
Alright, I'll take a look into it. Thanks for the detailed report and reproduction!

**Comment by charleskorn** [comment]
I've just pushed a fix for this, and will publish a release shortly.

Thanks again for taking the time to report the issue and for providing a reproduction @ineffyble!
