### ISSUE TITLE
Nicer formatting for --list-tasks

### ISSUE THREAD

**Issue by ineffyble** [charleskorn/batect#66]
Our project has 63 tasks defined in our batect.yml, and as a result the output of `batect --list-tasks` can be a bit of a mess.

Something that our team found handy was adding "\n\t" to the start of every description - this means the description for each task is on a newline and indented, which greatly improves visibility.

Perhaps something like this could be incorporated into batect natively?

**Comment by charleskorn** [comment]
> Our project has 63 tasks defined

I'm intrigued - why so many tasks?

> Something that our team found handy was adding "\n\t" to the start of every description - this means the description for each task is on a newline and indented, which greatly improves visibility.
>
> Perhaps something like this could be incorporated into batect natively?

Something that's been on my radar for a while now is the ability to group the output from `--list-tasks` - would that also be helpful here?

Thanks again for all your feedback @ineffyble!

**Comment by charleskorn** [comment]
I've just added support for grouping the output of `--list-tasks`, and this will be part of v0.27 (which I'm planning to release soon).

Please take a look at it and let me know if this isn't enough for your situation and we can discuss other possible solutions.
