### ISSUE TITLE
Support for YAML aliases

### ISSUE THREAD

**Issue by ineffyble** [charleskorn/batect#67]
Something I've found very helpful with writing build pipelines for GoCD is using YAML aliases - which let you define a block of code (an object or array) once, and then reuse it in multiple places, without rewriting.

This would be very useful for helping to make our batect.yml smaller and more readable (it's currently over 600 lines!).

I tried to use a YAML alias, but got a message that YAML aliases are not supported by whichever YAML parser you're currently using.

**Comment by charleskorn** [comment]
> it's currently over 600 lines!

😱 

> I tried to use a YAML alias, but got a message that YAML aliases are not supported by whichever YAML parser you're currently using.

This makes sense to me as something to add support for. I'm also interested in both why your config is so big and what is duplicated - are you able to share an example so I can understand how you would want to use this?

**Comment by ineffyble** [comment]
I think #58 might solve a lot of the use cases I'd have for aliases

**Comment by charleskorn** [comment]
Hi @ineffyble, thanks again for all your feedback. I've just added support for YAML aliases and anchors, and it will be part of v0.27 (which I'm planning to release soon).

There will be a bunch of examples of this on the [configuration docs page](https://batect.charleskorn.com/config/Overview.html) once I push out the release later today.
