### ISSUE TITLE
Improve error message for Java versions less than 8

### ISSUE THREAD

**Issue by Letitia-May** [charleskorn/batect#7]
When Java version was 1.7 I got the following error:

![screen shot 2018-05-28 at 6 10 44 pm](https://user-images.githubusercontent.com/9855395/40838990-e801f48e-65e3-11e8-8e01-9caa27467f1c.png)

**Comment by charleskorn** [comment]
Thanks for the bug report @Letitia-May!

This is definitely something that needs to be fixed... while it is mentioned in a number of places that Java 8+ is required, that error message could be much, much clearer and tell you exactly what's wrong.

**Comment by Letitia-May** [comment]
Thanks Charles! I didn't even realise I still had 1.7 installed and set as the default - so a clearer error message would have definitely helped in realising this was the issue sooner :)

**Comment by charleskorn** [comment]
(also, GitHub tells me this is your first ever issue on GitHub... congratulations :tada: )

**Comment by Letitia-May** [comment]
It is, thanks! 😄

**Comment by charleskorn** [comment]
This has been fixed with 27d53b6 and will be part of the next release.

Thanks again @Letitia-May!
