### ISSUE TITLE
Add support for --init to make using Node easier

### ISSUE THREAD

**Issue by pameck** [charleskorn/batect#74]
I am running a Node express server with batect. When I input `ctrl + c` in the terminal, it does not kill the process, instead it just hangs. 

With the attached project by running `./batect api` and then `ctrl +c` I'm able  to reproduce the bug. 
[sigterm-error-project.zip](https://github.com/charleskorn/batect/files/3047553/sigterm-error-project.zip)

I've also experienced this error with an nginx container but instead of hanging it displays the following message, but nothing happens after that: 

```
Error: Interrupt received during execution.
User interrupted execution.
```

**Comment by pameck** [comment]
I've been trying to debug this one but I haven't been able to progress much. [In this fork](https://github.com/pameck/batect/commit/cdd94f6d46cc9d713df32d220ec4eda8194f07f8) there is some code to reproduce the error.

Also, in the example project attached to the bug, I noticed that if I capture the `SIGINT` within the container first, then the process is correctly killed. Maybe that gives light into what might be happening. 

server.js would be now: 

``` javascript
const express = require('express');
const app = express();

app.get('/health', (req, res) => res.status(200).send());
const server = app.listen(3000);

process.on('SIGINT', () => {
    server.close();
});
```

**Comment by pameck** [comment]
After reading [this article](https://blog.ghaiklor.com/avoid-running-nodejs-as-pid-1-under-docker-images-when-running-them-on-mesosphere-kubernetes-or-b7bd505657f9), I altered the sample project to test the solution for killing the container with `CTRL C` which is running the image with the `--init` flag. 

`CTRL C` fails when trying to kill the container after having it run with the following command:
`docker run node-image-sigint`

but it correctly kills it if I run the container with 
`docker run --init node-image-sigint`

[node-image-sigint.zip](https://github.com/charleskorn/batect/files/3068206/node-image-sigint.zip)

Is there anyway to add the same flag when running images with batect?

**Comment by charleskorn** [comment]
Right, so this isn't a bug in batect per se, but an issue with Node. Adding support for `--init` makes sense to me.

**Comment by charleskorn** [comment]
Are you OK for me to close this now that #81 has been merged?

**Comment by pameck** [comment]
Yes, I'll test v30 tomorrow against the other container that's been failing to exit.

**Comment by charleskorn** [comment]
Did you have a chance to try this @pameck?
