### ISSUE TITLE
Consider using ".batect" as example folder name instead of "dev-infrastructure"

### ISSUE THREAD

**Issue by ineffyble** [charleskorn/batect#79]
This is an observation from a couple of projects.

Containing your `Dockerfile` definitions for batect containers in `.batect/` makes them tidier/more out of the way, especially when they're being used purely to run tasks (and there's not any `Dockerfile` definitions for your actual app, for example).

It also is less confusing than `dev-infrastructure` which leads my mind to cloud servers and Terraform.

**Comment by charleskorn** [comment]
That's a nicer name for it, I was never super happy with `dev-infrastructure`. 

Would you be interested in submitting a PR for this for the sample projects and docs?

**Comment by charleskorn** [comment]
I've updated the sample projects and documentation to reflect this. Thanks again for the suggestion @ineffyble!
