### ISSUE TITLE
First time user install confusion

### ISSUE THREAD

**Issue by andeemarks** [charleskorn/batect#8]
The instructions 'Download the latest version of batect from the releases page, and copy it into your project.' are correct, but the [releases page](https://github.com/charleskorn/batect/releases) contains 4 artefacts where it seems only the script is needed to download.  Strictly speaking, this is exactly what the above instruction is telling people, but I considered downloading the JAR as well, which seems redundant.

p.s  This is an extremely minor thing.

**Comment by charleskorn** [comment]
Hey @andeemarks, thanks for the feedback.

I'm a little unclear which page you're referring to - which page has the instructions you're referring to on them?

**Comment by charleskorn** [comment]
I've added some clarification in a225dba, and the docs site will be updated when the next release goes out.

Thanks again for the feedback!
