### ISSUE TITLE
Allow adding or dropping Docker capabilities

### ISSUE THREAD

**Issue by ineffyble** [charleskorn/batect#80]
The `container` spec should allow specifying [Docker capabilities](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities). See [docker-compose documentation](https://docs.docker.com/compose/compose-file/#cap_add-cap_drop) for an example implementation.

This functionality would be useful:

A) When wanting to tighten security, by allowing the user to drop unused capabilities

B) When needing to run a Docker container/task with extra capabilities (for example, adding `SYS_MODULE` to enable something in a container to load a kernel module)

I would suggest the `privileged` flag should also be part of this flag. This enables a range of extra privileges on a container, and is used for things like accessing host devices.

**Comment by charleskorn** [comment]
Great minds think alike... I added this to [the roadmap](https://github.com/charleskorn/batect/blob/master/ROADMAP.md) on Friday, and I nearly have a change ready to go to add support for `--privileged`. The capabilities stuff shouldn't be too hard to add either.

**Comment by charleskorn** [comment]
`--privileged` was added as part of [v0.29](https://github.com/charleskorn/batect/releases/tag/0.29.0) and adding and dropping capabilities will be part of v0.31, which should be out in the next few days.

Thanks again for all your feedback @ineffyble!
