### ISSUE TITLE
Support build context

### ISSUE THREAD

**Issue by nesl247** [charleskorn/batect#86]
I can't seem to be able to replicate the structure that we currently have. We have `docker/php/Dockerfile`, but I need the image to have access to `.` as the build context.

Am I missing something here?

**Comment by charleskorn** [comment]
Hi @nesl247, you're not missing anything :) 

At the moment, batect expects that your Dockerfile is in `build_directory` - that forms the root of the build context.

However, adding support for Dockerfiles in other locations wouldn't be too tricky, so I'm happy to add it. Watch this space.

**Comment by nesl247** [comment]
Thanks @charleskorn!

**Comment by charleskorn** [comment]
I've just pushed this change and it will be part of the 0.31 release which should be out in the next few days.

Thanks for your feedback @nesl247!

**Comment by nesl247** [comment]
Thanks for the quick work! We're excited to give batect a shot.
