### ISSUE TITLE
Add support for environment variables in build_args

### ISSUE THREAD

**Issue by nesl247** [charleskorn/batect#87]
As https://docs.docker.com/compose/compose-file/#args has the feature

> You can omit the value when specifying a build argument, in which case its value at build time is the value in the environment where Compose is running.

It would be really useful here as well. Our use case is we pass a `GITHUB_TOKEN` in order to install private dependencies, to a multi-stage Dockerfile.

See #68 for the same feature but for `environment`.

**Comment by charleskorn** [comment]
Just to be clear, batect already supports passing environment variables from the host to a container with a verbose syntax (`SOME_ENVIRONMENT_VARIABLE: $SOME_ENVIRONMENT_VARIABLE`), but #68 is asking for a concise syntax for the situation where the name of the environment variable on the host matches the desired name in the container. 

At the moment, batect doesn't support either of these things for build args. Adding support for the verbose syntax to build args is relatively straightforward, but the concise syntax will be more difficult (as the current proposal requires a breaking change to the configuration file syntax and I don't want to do that if I don't need to).

**Comment by nesl247** [comment]
I didn't realize it didn't support it at all in build_args. We were waiting on the other issue to be solved as it was a blocker for us so we hadn't gotten even as far as this building.

Given that `build_args` don't support environment variables at all, this is another blocker for us.

I would love to have at least the verbose syntax, though I would treat build_args the same as environment variables. I think a lot of users will be coming from docker-compose, and not having a similar featureset will be making the change a little harder.

**Comment by charleskorn** [comment]
Makes complete sense, I agree with prioritising `build_args` supporting environment variables over the more concise syntax for either `build_args` or `environment`. I'll take a look when I get a chance.

> We were waiting on the other issue to be solved as it was a blocker for us so we hadn't gotten even as far as this building.

Are you referring to #86 here?

**Comment by nesl247** [comment]
@charleskorn Yep! And thanks again!

**Comment by charleskorn** [comment]
Hey @nesl247, sorry for the slow response to this (I've been moving house). I've implemented this and it should go out in the next release, which should be out in the next day or two.

**Comment by nesl247** [comment]
Nothing to apologize for. Thanks for all of your hard work! Hope you enjoy your new house.

Looking forward to trying out batect again.
