### ISSUE TITLE
Batect doesn't work with Java 10

### ISSUE THREAD

**Issue by minnn-minnn** [charleskorn/batect#9]
Returns error: 

./batect: line 62: ((: 0 2018-04-17: syntax error in expression (error token is "2018-04-17")

Output of java -version:

java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)

**Comment by charleskorn** [comment]
Thanks for the bug report @minnn-minnn, I'll take a look.

**Comment by charleskorn** [comment]
This has been fixed with 23e6d63 and will be part of the next release.

Thanks again @minnn-minnn!

(also, GitHub tells me this is your first ever issue on GitHub... congratulations 🎉)
